@EmployeeManager_VR.Server_HostAddress = http://localhost:5284

GET {{EmployeeManager_VA.Server_HostAddress}}/employee/
Accept: application/json

###

POST {{EmployeeManager_VA.Server_HostAddress}}/employee/
accept: application/json

###

DELETE {{EmployeeManager_VA.Server_HostAddress}}/employee/
accept: application/json

####

GET {{EmployeeManager_VA.Server_HostAddress}}/department/
Accept: application/json

###

POST {{EmployeeManager_VA.Server_HostAddress}}/department/
accept: application/json

###


DELETE {{EmployeeManager_VA.Server_HostAddress}}/department/
accept: application/json

####
